version: 2.1

orbs:
  sonatype: sonatype-nexus-community/circleci-maven-release-orb@0.0.16
  sonatype-dryrun: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u171-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS=-Xmx3600m 
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # check 
      - run: mvn apache-rat:check

      # run test and package
      - run: mvn clean package

      # Save JUnit result.
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports

      # run site
      - run: mvn site

      - run:
          command: |
            cp -r ./target/site ~/site

      - store_artifacts:
          path: ~/site

custom_filters:
  master_only: &master_only
    filters:
      branches:
        only: master
  master_ignore: &master_ignore
    filters:
      branches:
        ignore: master

workflows:
  build-and-test:
    jobs:
      - build:
          <<: *master_ignore
  run-release:
    jobs:
      - build:
          <<: *master_only
      - sonatype-dryrun/run-maven-release:
          <<: *master_only
          requires:
            - build
          mvn-release-perform-command: |
            mvn --batch-mode release:perform -DdryRun=true -s .circleci/.maven.xml
          mvn-release-prepare-command: |
            mvn --batch-mode release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " -DdryRun=true -s .circleci/.maven.xml
          ssh-fingerprints: 2c:6a:fe:b9:63:a9:01:b7:74:30:55:c2:5d:14:f5:fe
      - approve:
          type: approval
          <<: *master_only
          requires:
            - sonatype-dryrun/run-maven-release
      - sonatype/run-maven-release:
          <<: *master_only
          requires:
            - approve
          ssh-fingerprints: 2c:6a:fe:b9:63:a9:01:b7:74:30:55:c2:5d:14:f5:fe